language: erlang
dist: xenial
sudo: required
addons:
    apt:
        packages:
        - libpam0g-dev
        - libexpat1-dev
        - odbc-postgresql
        - slapd
        - ldap-utils
        - golang # used for google drive test results upload
        - unixodbc # for mssql
        - tdsodbc   # for mssql
